export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAIL = "GOOGLE_LOGIN_FAIL";
export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN";
export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_FAIL = "FACEBOOK_LOGIN_FAIL";

export const ASYNC_LOADING = "ASYNC_LOADING";
export const ASYNC_COMPLETE = "ASYNC_COMPLETE";

export const GET_USER = "GET_USER";
